version: "3.12"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      network: host  # ビルド時にホストネットワークを利用
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload",]
    container_name: fastapi       
    depends_on:
      - db
    volumes:
      - ./backend:/backend:cached
      - ./.env:/backend/.env:ro
    networks:
      - public_network
      - internal_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      network: host  # ビルド時にホストネットワークを利用
    container_name: react-native
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    entrypoint: []
    command: ["npx", "expo", "start", "--web", "--host", "localhost"]
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend:cached
      - ./frontend/node_modules:/frontend/node_modules:ro
      - ./.env:/frontend/.env:ro
    networks:
      - internal_network
      - public_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    
  db:
    image: postgres:13
    container_name: postgres_mobile_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

networks:
  public_network:
    driver: bridge
  internal_network:
    internal: true   # 外部から隔離された内部ネットワーク

volumes:
  postgres_data:
  frontend_node_modules: {}
